### ISSUE TITLE
Loosing connection with KNX Router

### ISSUE THREAD

**Issue by resoai** [open-homeautomation/pknx#11] opened 2016-08-10 08:31 UTC
It looks like KNX component keeps disconnecting from the KNX router. I've noticed that at some point all switches stop working i.e. they stop receiving feedback from physical buttons and also if you try flipping any switch from HASS UI it just jumps back to off position in a second. The only way to solve it is to restart HASS. I've also tried setting logger to debug level but there are no error messages, just regular ones:

`16-08-09 11:59:18 homeassistant.core: Bus:Handling <Event call_service[L]: domain=homeassistant, service_data=entity_id=switch.av_room_spotlights, service=turn_on, service_call_id=140409023294376-42>`

Is there anything I can do to help you debug it? I've tried running HASS on wired RPI3 and moved to Ubuntu Server VM so it is nothing to do with power saving of WiFi in RPI. It would be nice to add more logging to see when and how it is loosing connection.

**Comment by open-homeautomation** [comment] 2016-08-10 08:40
Do you have any KNX components that send telegrams in regular intervals? If not, can you configure a component that it sends regular updates (e.g. every minute)? 
This would help to understand if the KNX IP interface drops the connection because there is no activity.

**Comment by resoai** [comment] 2016-08-10 09:00
I don't think it is something to do with inactivity since the connection lived overnight and than simply stopped working within seconds of flipping different switches. I think a good start would be to get more output via the logger i.e. if the connection was indeed lost or it is simply my assumption.

**Comment by open-homeautomation** [comment] 2016-08-10 09:11
Adding more logging is complicated without knowing what to log.
Can you reproduce the problem with a specific scenario or does it just happen randomly?

**Comment by resoai** [comment] 2016-08-10 09:27
It happens randomly so it is nearly impossible to know exact conditions as to when to expect it. It would be good to at least log reply from KNX Router i.e. if the command has been received/accepted (if it is at all possible).

**Comment by resoai** [comment] 2016-08-10 09:44
Could you please advise example config for some dummy regular telegrams to test it? I'm sorry it is my 4th day with HAAS.

**Comment by open-homeautomation** [comment] 2016-08-10 09:46
I will try to build a config for this. This might take some time as I'm a bit busy at the moment.

**Comment by resoai** [comment] 2016-08-10 12:32
I have created a basic automation that keeps switching lights on in one room and can confirm that connection keeps stable:

`- alias: 'KNX Keepalive'
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  action:
    service: switch.turn_on
    entity_id: switch.guest_room_spotlights`

So this is indeed a problem with inactivity.

**Comment by open-homeautomation** [comment] 2016-08-10 12:35
Cool, thanks for this feedback. I will implement some kind of keep-alive messages and also check if the connection is still working. 
It will just need some time.

**Comment by resoai** [comment] 2016-08-10 12:56
Thanks! I've created a dummy hidden switch with a non-existent endpoint which is being switched on every minute, so hopefully it will work as a temporary fix. May I also suggest to extend KNX component to allow push-buttons and sensors like weather stations etc?

**Comment by open-homeautomation** [comment] 2016-08-10 13:08
The KNX library supports all KNX components. It doesn't even know what kind of KNX component sends a message.

If you mean the Home Assistant integration: I can do this only for KNX components I have available for tests. As I don't have a KNX weather station, I can't implement this. 
Somebody has to sponsor a test device for development and debugging purposes or somebody else has to do the HA implementation. This isn't extremely complicated.

**Comment by resoai** [comment] 2016-08-10 13:18
I understand. Hopefully I will be able to sponsor you one day. It would also be nice to be able to set different modes in thermostat.

**Comment by daBONDi** [comment] 2016-08-10 14:06
I think it is because the keep alive/hearthbeat messege on the controlchannel is not implemented read something about this in knx spec

Will try to implement it and push a commit

Sorry for beeing so inactive on helping the project usula was quite busy...

**Comment by open-homeautomation** [comment] 2016-08-10 14:17
Yes, I think sending keepalive messages is needed. If you want to look into this, I won't touch this.

However, I will work on the send_tunneling_request method to make sure it closes the connection if it doesn't receive an ACK.

**Comment by open-homeautomation** [comment] 2016-08-10 21:05
Keepalive has been implemented now, but it has been tested only minimal. 
@resoai : Are you able to download the files from Github and replace them in your HASS installation for a test?

**Comment by resoai** [comment] 2016-08-10 22:05
Thank you. I've replaced the files from Github and restarted HASS. I will keep testing it tonight and tomorrow and will let you know if it solved the problem!

**Comment by resoai** [comment] 2016-08-10 22:40
Unfortunately this did not solve the problem but actually made it worse. Now it disconnects after few mins. I've enabled full debug logging and this is all I see in the logs:

16-08-10 23:37:21 homeassistant.core: Bus:Handling <Event call_service[L]: domain=homeassistant, service=turn_on, service_call_id=139931693521832-22, service_data=entity_id=group.kitchen>
16-08-10 23:37:21 homeassistant.core: Bus:Handling <Event call_service[L]: domain=switch, service=turn_on, service_call_id=139931693521832-23, service_data=entity_id=['switch.kitchen_centre_pendant', 'switch.kitchen_island_pendants', 'switch.kitchen_spotlights', 'switch.kitchen_wall_lights']>
16-08-10 23:37:21 root: [6, 16, 4, 32, 0, 21]
16-08-10 23:37:21 root: [4, 67, 44, 0, 17, 0, 188, 224, 0, 0, 9, 9, 1, 0, 129]
16-08-10 23:37:22 root: [6, 16, 4, 32, 0, 21]
16-08-10 23:37:22 root: [4, 67, 44, 0, 17, 0, 188, 224, 0, 0, 9, 9, 1, 0, 129]
16-08-10 23:37:23 root: Disconnecting KNX/IP tunnel...
16-08-10 23:37:23 root: [6, 16, 2, 9, 0, 16]
16-08-10 23:37:23 root: [67, 0, 8, 1, 192, 168, 1, 90, 183, 71]
16-08-10 23:37:23 root: Got value of group address 2569 from cache: [0]
16-08-10 23:37:23 root: Got value of group address 2569 from cache: [0]
16-08-10 23:37:23 root: Got value of group address 2569 from cache: [0]
16-08-10 23:37:23 root: [6, 16, 4, 32, 0, 21]
16-08-10 23:37:23 root: [4, 67, 46, 0, 17, 0, 188, 224, 0, 0, 9, 11, 1, 0, 129]

**Comment by open-homeautomation** [comment] 2016-08-11 05:37
Hmm, it seems that your gateway does not respond to our Connection state requests. This is a bit strange. In this case the software disconnects the gateway.
I've uploaded a new version that automatically re-connects in this case. Can you try this one (you only need to change the ip.py file).
This will result in a lot of disconnect/connect requests, but at least from HASS point of view it should be stable. I still have to find out why your gateway does not respond to the connection state requests.

**Comment by resoai** [comment] 2016-08-11 08:56
Thanks, I've updated the file, deleted cache and restarted HASS. I will keep you posted on how it behaves.  May I suggest to look at openhab's implementation of KNX binding? It looks like they expose a few options for timeouts, read retries and auto reconnect period. 

https://github.com/openhab/openhab/wiki/KNX-Binding

**Comment by resoai** [comment] 2016-08-11 09:00
I'm sorry to say but the issue has not been resolved. Here is what I see in logs:

```
16-08-11 09:58:11 homeassistant.components.knx: Unable to read from KNX address: 2314 (None)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:32 root: KNX IP tunnel connect error:(Channel: 0, Status: 36)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2305 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2315 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2377 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2453 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2385 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2309 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2387 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2314 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2313 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2434 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 14594 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2316 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2436 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 16130 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2386 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2435 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2433 (None)
16-08-11 09:58:33 homeassistant.components.knx: Unable to read from KNX address: 2306 (None)
16-08-11 09:58:34 root: KNX/IP gateway did not respond to connect request
```

**Comment by open-homeautomation** [comment] 2016-08-11 09:05
What KNX gateway are you using?

**Comment by resoai** [comment] 2016-08-11 09:21
It is Siemens 5WG1 146-1AB02 IP Router.

**Comment by daBONDi** [comment] 2016-08-13 19:48
@resoai can you make a Wireshark sniff with protocol "knx" from your haas server

So we can debug what is send between the KNX GW and the hass?

**Comment by daBONDi** [comment] 2016-08-13 20:43
@resoai Try follow new ip.py file
Waiting for a pull Request #13 but you can try it in the meantime

https://github.com/daBONDi/pknx/blob/a8aa44b233323ced7bef5d124aafebd92483cf52/knxip/ip.py

**Comment by daBONDi** [comment] 2016-08-13 21:27
@resoai 
Do you try to change something with ETS on the KNXBus over the Gateway or going into Busmonitor Mode?

**Comment by resoai** [comment] 2016-08-14 07:53
Thanks, I'm going to to try ip.py file now! I'm not changing anything with ETS, I don't even have a license for it since it was all installed by previous home owner.

**Comment by daBONDi** [comment] 2016-08-14 16:56
Pls also make a network sniff with wireshark and the filter "knx"

**Comment by resoai** [comment] 2016-08-14 20:36
I'm sorry I'm new to Wireshark so it will take a bit of time for me. I am however happy to say that this appears to have fixed the issue and I have not experienced any  disconnects for the whole day!

**Comment by resoai** [comment] 2016-08-14 21:01
Strangely I don't see any traffic from KNX router via Wireshark, I've even tried a simple display filter "ip.addr==192.168.1.11".

**Comment by daBONDi** [comment] 2016-08-15 09:03
N1 to here that, If your issue is fixed now then the problem was the missing heartbeat feature and we dont need the network sniff anymore

Do you select the correct networkinterface?

If you are on Windows check that winpcap is installed and service is runnimg

**Comment by open-homeautomation** [comment] 2016-08-15 09:26
?ve merged this pull request now. I will do some more testing and create a new library version.

**Comment by resoai** [comment] 2016-08-15 10:25
Thanks! Yes, winpcap is installed and I can see other traffic within the network just fine. In any event I would like to thank everyone for fixing the problem!

**Comment by daBONDi** [comment] 2016-08-15 16:06
Thx for posting and testing it without colab nothing would be fixed or created in the opensource world

**Comment by open-homeautomation** [comment] 2016-08-15 19:30
I've packaged a new 0.3.3 version, uploaded it and created a pull request to Home assistant. This fix should be included in next next release (0.27)

**Comment by resoai** [comment] 2016-08-15 20:55
Great!

**Comment by daBONDi** [comment] 2016-08-18 19:26
Think we can close this, looks like its fixed

**Closed** 2016-08-19 10:25 UTC
Labels: bug
